[build-system]
requires = [
    "setuptools",  # FIXME: declare min/max setuptools versions?
    "Cython; python_version < '3.13'",
    "Cython>=3.0; python_version >= '3.13'"
]
backend-path = ["packaging"]
build-backend = "_pyyaml_pep517"
