[build-system]
requires = [
    "setuptools>=77.0.0",
    "wheel",
    "Cython; python_version < '3.13'",
    "Cython>=3.0; python_version >= '3.13'"
]
backend-path = ["packaging"]
build-backend = "_pyyaml_pep517"
